// Checks on the site's source files themselves, for rules that no page render can show.
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const root = fileURLToPath(new URL('../..', import.meta.url))
const read = (file: string) => readFileSync(path.join(root, file), 'utf8')

function pageFiles(folder: string, file = 'page.tsx'): string[] {
  return readdirSync(path.join(root, folder)).flatMap((name) => {
    const relative = path.join(folder, name)
    if (statSync(path.join(root, relative)).isDirectory()) return pageFiles(relative, file)
    return name === file ? [relative] : []
  })
}

// Does this source read the database? Yes when it calls getPayload, or imports a value (not only a
// type) from payload or the Payload config, or imports from a src/lib helper that itself reads the
// database. It does not see a database read hidden in a component or a package the page imports.
const DATA_IMPORT = /^import (?!type\b)[^;]*?from '(payload|@payload-config|@\/payload\.config)'/m

function readsTheDatabase(source: string): boolean {
  if (/\bgetPayload\b/.test(source) || DATA_IMPORT.test(source)) return true
  return [...source.matchAll(/^import (?!type\b)[^;]*?from '@\/lib\/([\w/-]+)'/gm)].some(([, name]) => {
    const file = ['.ts', '.tsx'].map((ext) => `src/lib/${name}${ext}`).find((candidate) => existsSync(path.join(root, candidate)))
    return file ? readsTheDatabase(read(file)) : false
  })
}

describe('the public pages read the database on every visit, never during the build', () => {
  it('knows which imports read the database', () => {
    expect(readsTheDatabase("import config from '@payload-config'")).toBe(true)
    expect(readsTheDatabase("import config from '@/payload.config'")).toBe(true)
    expect(readsTheDatabase("import { getPayload } from 'payload'")).toBe(true)
    expect(readsTheDatabase("import { findPage } from '@/lib/pages'")).toBe(true)
    expect(readsTheDatabase("import type { Page } from '@/payload-types'")).toBe(false)
    expect(readsTheDatabase("import type { Metadata } from 'payload'")).toBe(false)
    expect(readsTheDatabase("import { formatPrice } from '@/lib/format'")).toBe(false)
  })

  it("every page under src/app/(site) that reads the database says dynamic = 'force-dynamic'", () => {
    const pages = pageFiles('src/app/(site)').filter((file) => readsTheDatabase(read(file)))
    // The home page, the clinic list, the plain pages and Contact, at least.
    expect(pages.length).toBeGreaterThanOrEqual(4)
    for (const file of pages) {
      expect(read(file), file).toMatch(/^export const dynamic = 'force-dynamic'$/m)
    }
  })

  it("every route handler under src/app/api that reads the database says dynamic = 'force-dynamic'", () => {
    // Payload's own routes (src/app/(payload)) are generated by Payload and left as they are.
    const routes = pageFiles('src/app/api', 'route.ts').filter((file) => readsTheDatabase(read(file)))
    // The course check, at least.
    expect(routes).toContain(path.join('src/app/api/course-check/route.ts'))
    for (const file of routes) {
      expect(read(file), file).toMatch(/^export const dynamic = 'force-dynamic'$/m)
    }
  })
})

describe("the site's name in the browser tab", () => {
  it('is written once: the layout adds it to every title, and no page writes it itself', () => {
    expect(read('src/app/(site)/layout.tsx')).toMatch(/^\s*title: SITE_TITLE,$/m)
    const files = [...pageFiles('src/app/(site)'), 'src/lib/pages.ts']
    const named = files.filter((file) => /·\s*Campus Cycle/.test(read(file)))
    expect(named, "give only the page's own title; the layout adds \" · \" and the name").toEqual([])
    // The "not found" page gets no title from the layout, so it adds the name from the same constant.
    expect(read('src/app/(site)/not-found.tsx')).toContain('<title>{`Page not found · ${SITE_NAME}`}</title>')
  })
})

describe('the markers a course exercise points at', () => {
  it('Hero.tsx keeps the W4 line, right above the tagline it is about', () => {
    const lines = read('src/components/site/Hero.tsx').split(/\r?\n/)
    const marker = lines.indexOf('// W4: put your own name in this tagline')
    expect(marker).toBeGreaterThan(-1)
    expect(lines[marker + 1]).toMatch(/^const TAGLINE = '/)
  })

  it('the clinic page keeps the W5 line where the summary is shown, and the price list above the booking form', () => {
    const source = read('src/app/(site)/clinics/[slug]/page.tsx')
    const lines = source.split(/\r?\n/)
    // A learner adds their list on the line AFTER this comment; the comment and the summary stay.
    const keep = 'Keep the W5 comment and the summary above it; put your list on the line after the comment.'
    const marker = lines.findIndex((line) => line.trim() === `{/* W5: show the clinic's "What to bring" list here, the same way this page shows its prices below. */}`)
    expect(marker, keep).toBeGreaterThan(-1)
    // The summary is shown just above the marker.
    expect(lines.slice(marker - 4, marker).join('\n'), keep).toContain('clinic.summary')
    // The pattern the W5 line points at, in this same file, below it: a Prices heading and a list made
    // with .map, shown only when there is something in the list (no heading on its own). The learner's
    // own list may sit between the comment and it.
    const markerAt = source.indexOf(lines[marker].trim())
    const guard = source.indexOf('{repairs.length > 0 && (', markerAt)
    expect(guard, keep).toBeGreaterThan(markerAt)
    const prices = source.slice(guard, source.indexOf('</section>', guard))
    expect(prices).toContain('<h2 id="prices"')
    expect(prices).toContain('<ul')
    expect(prices).toContain('repairs.map(')
    expect(source.indexOf('<BookingForm')).toBeGreaterThan(guard + prices.length)
  })

  it('BookingForm.tsx keeps the W6 repair choice commented out, with the name only and the exact price comment on the label line', () => {
    const source = read('src/components/site/BookingForm.tsx')
    const lines = source.split(/\r?\n/)
    // The label line, exactly: commented out, the repair's name only, and the full comment.
    const labelLine =
      "//         const label = repair.name // To show the price in the choice too, add the record's price here (formatPrice(repair.price)): it reads the stored price, nothing is copied. Also import formatPrice from '@/lib/format', as the clinic page does."
    expect(lines.filter((line) => line.trim() === labelLine)).toHaveLength(1)
    // The instructions: replace the whole placeholder line, and the server's two W6 lines.
    expect(source).toContain('{/* W6: <RepairChoice repairs={props.repairs} /> */}')
    expect(source).toContain('// Then replace the whole line {/* W6: <RepairChoice repairs={props.repairs} /> */} in the form below\n// with <RepairChoice repairs={props.repairs} />.')
    expect(source).toContain('the two lines the W6 comment in\n// createBooking.ts names (src/tasks/book-slot/createBooking.ts).')
    // The block is commented out as a whole: no line that uses the repairs is live code.
    const live = lines.filter((line) => !line.trimStart().startsWith('//') && !line.trimStart().startsWith('{/*') && !line.trimStart().startsWith('*'))
    expect(live.join('\n')).not.toMatch(/name="repairs"|RepairChoice repairs=/)
    expect(lines.some((line) => /^\s*\/\/\s+<input type="checkbox" name="repairs"/.test(line))).toBe(true)
    // formatPrice, which the comment names, lives in src/lib/format.ts.
    expect(read('src/lib/format.ts')).toMatch(/^export function formatPrice\(/m)
  })

  it('createBooking.ts keeps the W6 repairs line commented out, next to the whitelist', () => {
    const source = read('src/tasks/book-slot/createBooking.ts')
    expect(source).toMatch(/^\s*\/\/\s*const repairs = formData\.getAll\('repairs'\)/m)
    expect(source).not.toMatch(/^\s*const repairs = formData\.getAll/m)
    // ...and `repairs,` in payload.create, commented out too, under the W6 comment that names both.
    expect(source).toMatch(/^\s*\/\/ W6: switch on the repair choice\./m)
    expect(source).toMatch(/^\s*\/\/\s*repairs,\s*$/m)
  })
})

describe("shadcn/ui's folders (components.json)", () => {
  const { aliases } = JSON.parse(read('components.json')) as { aliases: Record<string, string> }
  const tsconfig = JSON.parse(read('tsconfig.json')) as { compilerOptions: { paths: Record<string, string[]> } }

  it('every alias is an @/ address, which tsconfig.json maps to src/', () => {
    expect(tsconfig.compilerOptions.paths['@/*']).toEqual(['./src/*'])
    for (const [name, alias] of Object.entries(aliases)) expect(alias, name).toMatch(/^@\//)
  })

  it('the aliases point at files and folders that exist (hooks: shadcn makes that folder when a part needs it)', () => {
    const target = (alias: string) => path.join(root, 'src', alias.slice(2))
    expect(existsSync(`${target(aliases.utils)}.ts`), aliases.utils).toBe(true)
    for (const name of ['components', 'ui', 'lib']) {
      expect(statSync(target(aliases[name])).isDirectory(), aliases[name]).toBe(true)
    }
  })

  it('@/lib/utils gives the cn a shadcn part imports, and a later Tailwind class wins', async () => {
    const { cn } = await import('@/lib/utils')
    expect(cn('min-h-9 px-3', 'min-h-11')).toBe('px-3 min-h-11')
  })
})
